---
title: "broadneon"
author: "sbsambado"
date: "10/5/2020"
output: html_document
---

```{r}
ticks_taxa <- read.csv("/Users/samanthasambado/Macrosystems/filesToStack10093/stackedFiles/tck_taxonomyProcessed.csv", header=T)

ticks_taxa$site <- substr(ticks_taxa$plotID, 1, 4)

unique(ticks_taxa$site)
ticks_taxa <- ticks_taxa[which(ticks_taxa$scientificName == 'Ixodes scapularis'),]
# treat plot ID as character
ticks_taxa$plotID <- lapply(ticks_taxa$plotID, as.character)

# extract certain plots
ticks_taxa$siteID <- substr(ticks_taxa$plotID, 1, nchar(ticks_taxa$plotID)-4)

ticks_taxa2 <- ticks_taxa[,c(3,4,8,23,24,33)]

#I_scap_N <- ticks_taxa2[which(ticks_taxa2$sexOrAge == 'Nymph' & ticks_taxa2$scientificName == 'Ixodes scapularis'),]
#head(I_scap_N)
#nrow(I_scap_N)

I_scap_N <- ticks_taxa2[which(ticks_taxa2$sexOrAge == 'Nymph'),]

sapply(I_scap_N, class)
I_scap_N$collectDate <- as.character(I_scap_N$collectDate)

I_scap_N$collectDate <- substr(I_scap_N$collectDate, 1, nchar(I_scap_N$collectDate)-7)
#head(I_scap_N)

I_scap_N$collectDate <- as.factor(I_scap_N$collectDate)
I_scap_N$plotID <- unlist(I_scap_N$plotID)
I_scap_N$collectDate <- as.character(I_scap_N$collectDate)
I_scap_N$Year <- substr(I_scap_N$collectDate, 1, nchar(I_scap_N$collectDate)-6)
#head(I_scap_N)

#library(lubridate)
I_scap_N$Month <-month(as.POSIXlt(I_scap_N$collectDate, format = "%Y-%m- %d"))

unique(I_scap_N$site)

```

give regions
```{r}

I_scap_N$region <- I_scap_N$site
I_scap_N$region[I_scap_N$site == "BART"] <- "northeast"
I_scap_N$region[I_scap_N$site == "HARV"] <- "northeast"
I_scap_N$region[I_scap_N$site == "BLAN"] <- "midatlantic"
I_scap_N$region[I_scap_N$site == "SCBI"] <- "midatlantic"
I_scap_N$region[I_scap_N$site == "SERC"] <- "midatlantic" 
I_scap_N$region[I_scap_N$site == "STEI"] <- "great lakes"
I_scap_N$region[I_scap_N$site == "TREE"] <- "great lakes"
I_scap_N$region[I_scap_N$site == "UNDE"] <- "great lakes"
I_scap_N$region[I_scap_N$site == "OSBS"] <- "southeast"
I_scap_N$region[I_scap_N$site == "KONA"] <- "praire peninsula"
I_scap_N$region[I_scap_N$site == "KONZ"] <- "praire peninsula"
I_scap_N$region[I_scap_N$site == "UKFS"] <- "praire peninsula"
I_scap_N$region[I_scap_N$site == "GRSM"] <- "appalachians"
I_scap_N$region[I_scap_N$site == "MLBS"] <- "appalachians"
I_scap_N$region[I_scap_N$site == "ORNL"] <- "appalachians"
I_scap_N$region[I_scap_N$site == "DELA"] <- "ozarks"
I_scap_N$region[I_scap_N$site == "LENO"] <- "ozarks"
I_scap_N$region[I_scap_N$site == "TALL"] <- "ozarks"
I_scap_N$region[I_scap_N$site == "RMNP"] <- "southern rockies"
I_scap_N$region[I_scap_N$site == "OAES"] <- "southern plaines"
I_scap_N$region[I_scap_N$site == "ABBY"] <- "pacific northwest"

 

#View(I_scap_N)

```


```{r}
I_scap_N_regions <- I_scap_N[which(I_scap_N$region != 'pacific northwest' & I_scap_N$region != 'southern plaines' & I_scap_N$region != 'southern rockies'),]

DateVec16<- seq(from = as.Date("2016-03-01"), to = (as.Date("2016-11-30")), by = 1)
DateVec17<- seq(from = as.Date("2017-03-01"), to = (as.Date("2017-11-30")))
DateVec18<- seq(from = as.Date("2018-03-01"), to = (as.Date("2018-11-30")))
DateVec18<- seq(from = as.Date("2019-03-01"), to = (as.Date("2019-11-30")))

#library(ggplot2)
ggplot(data = I_scap_N_regions,
aes(y = individualCount, x = collectDate))+
  facet_wrap(~region, scale = 'free_y',ncol = 3)+
  theme(strip.background = element_rect(fill = 'gray95'))+
  theme(strip.text.x = element_text(face = 'bold'))+
  geom_point() +
  #geom_smooth(se = FALSE, color = 'red')+
  stat_smooth(geom='ribbon', aes(ymin = ifelse(..ymin.. < 0, 0, ..ymin..)), alpha = .3)+
  clean_background +
  theme(axis.text.x = element_text(angle = 45, size = 2, vjust = 0.5))+
  ytitletheme +
  xtitletheme 
```

```{r}
tick_path <- read.csv("/Users/samanthasambado/Macrosystems/filesToStack10092/stackedFiles/tck_pathogen.csv", header=T)

Tick_path <- tick_path[,c(4,5,7,8,9,14,18,20,23,24)]
#head(tick_path, n=20)
#unique(tick_path$testPathogenName)

# select for LD spirochetes
# tick_path_Bb <- tick_path[which(tick_path$testPathogenName == 'Borrelia burgdorferi' | tick_path$testPathogenName == 'Borrelia burgdorferi sensu lato' | tick_path$testPathogenName == 'Borrelia sp.'),]

#nrow(tick_path_Bb)


#tick_path_Bb_pos <- tick_path_Bb[which(tick_path_Bb$testResult == 'Positive'),]
#nrow(tick_path_Bb_pos)
#unique(tick_path_Bb_pos$siteID)

unique(Tick_path$testPathogenName)
sum(Tick_path$individualCount)
Tick_path$incidence <- ifelse(Tick_path$testResult == 'Positive', 1, 0)
Tick_path$collectDate <- as.character(Tick_path$collectDate)
Tick_path$Date <- substr(Tick_path$collectDate, 1, nchar(Tick_path$collectDate)-7)
#head(Tick_path_Bb)
#nrow(Tick_path_Bb)
#View(Tick_path)
Tick_path_col <- aggregate(incidence ~ plotID + Date + testPathogenName, data=Tick_path, FUN=mean)
#head(Tick_path_Bb_col, n=20)
#nrow(Tick_path_Bb_col)

Tick_path_col$plotID <- as.character(Tick_path_col$plotID)
Tick_path_col$site <- substr(Tick_path_col$plotID, 1, nchar(Tick_path_col$plotID)-4)
#head(Tick_path_Bb_col)

Tick_path_col <- Tick_path_col[which(Tick_path_col$testPathogenName != 'HardTick DNA Quality' & Tick_path_col$testPathogenName != 'Ixodes pacificus'),]

unique(Tick_path_col$site)

Tick_path_col$site = factor(Tick_path_col$site,
                            levels = c("HARV","TREE",
                            "SCBI","SERC","BLAN", 
                            "KONZ","UKFS","KONA",
                            "MLBS","ORNL", 
                            "DELA","TALL" ,"LENO",
                            "OSBS"))

# Tick_path_Bb_col_E$site = factor(Tick_path_Bb_col_E$site, 
#                             levels = c("BART" ,"HARV", 
#                                         "UNDE" ,"TREE","STEI" ,
#                                         "BLAN" , "SCBI" ,"SERC",
#                                         "MLBS", "ORNL", "GRSM",
#                                         "TALL",
#                                        "OSBS"))
# 
# Tick_path_Bb_col_E$plotID = factor(Tick_path_Bb_col_E$plotID, 
#                             levels = c("HARV_001",
#                                        "HARV_002",
#                                        "HARV_004",
#                                        "HARV_006",
#                                        "HARV_020" ,
#                                        "HARV_022", 
#                                        "HARV_026" ,
#                                        "TREE_007",
#                                        "TREE_015",
#                                        "TREE_017",
#                                        "TREE_019",
#                                        "TREE_022",
#                                        "BLAN_005",
#                                        "BLAN_012",
#                                        "SERC_001",
#                                        "SERC_002",
#                                        "SERC_005",
#                                        "SERC_006",
#                                        "SERC_012",
#                                        "SERC_023",
#                                        "SCBI_002",
#                                        "SCBI_005",
#                                        "SCBI_006",
#                                        "SCBI_007",
#                                        "SCBI_013",
#                                        "SCBI_039",
#                                        "ORNL_002",
#                                        "ORNL_003",
#                                        "ORNL_007",
#                                        "ORNL_008",
#                                        "ORNL_009",
#                                        "ORNL_040")) 
# 

#Tick_path__col_E   <- subset(Tick_path_Bb_col_E, !is.na(plotID))                           
                                    
 #ggplot(as.data.frame(totalticks), aes(x = Site, y = individualCount))+
  # geom_point()
 



#d <- tableGrob(totalticks, rows = rownames(totalticks), cols = colnames(totalticks))
#grid.arrange(d)
#myt <- ttheme_default(
         # Use hjust and x to left justify the text
         # Alternate the row fill colours
                 #core = list(fg_params=list(hjust = 1, x=1),
                             #bg_params=list(fill=c("grey90", "grey88"))))
#c <-grid.draw(tableGrob(format(totalticks, big.mark=","), theme=myt, rows=NULL))

#tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)))
#tbl <- tableGrob(totalticks, rows=NULL, theme=tt)

                                  
                                       
# remove NA                                     
Tick_path_col <- subset(Tick_path_col, !is.na(testPathogenName))                           


  ggplot(Tick_path_col, aes(y = incidence, x = site, group = testPathogenName, color = testPathogenName))+
  geom_jitter(na.rm = TRUE, width = 1, alpha = .3)+
    clean_background+
    labs(y = 'Pathogen incidence rate', x = 'Site')+
    titleytheme+ xtitletheme+ rotatexaxistheme+
      theme(legend.position = 'bottom', legend.box = 'horizontal', 
            legend.title = element_text(size = 6), legend.text = element_text(size = 5))
#ggsave("PathogenIncidenceTicksSite_v2.pdf", dpi = 320)

 Tick_path_col_no0 <- Tick_path_col[which(Tick_path_col$incidence > "0"),]
ggplot(Tick_path_col_no0, aes(y = incidence, x = site, group = testPathogenName, color = testPathogenName))+
  geom_jitter(na.rm = TRUE, width = .9, alpha = .3, size = 3)+
    clean_background+
    labs(y = 'Pathogen incidence rate', x = 'Site')+
    titleytheme+ xtitletheme+ rotatexaxistheme+
      theme(legend.position = 'bottom', legend.box = 'horizontal', 
            legend.title = element_text(size = 6), legend.text = element_text(size = 5))
ggsave("PathogenIncidenceTicksSite_v3.pdf", dpi = 320)
 

# # remove ricketssia
#   Tick_path_col_norick <- Tick_path_col[which(Tick_path_col$testPathogenName != 'Ehrlichia muris-like'),]
# 
# ggplot(Tick_path_col_norick, aes(y = incidence, x = site, group = testPathogenName, color = testPathogenName))+
#   geom_jitter(na.rm = TRUE, width = 1, alpha = .3)+
#     clean_background+
#     labs(y = 'Pathogen incidence rate', x = 'Site')+
#     titleytheme+ xtitletheme+ rotatexaxistheme+
#       theme(legend.position = 'bottom', legend.box = 'horizontal', 
#             legend.title = element_text(size = 6), legend.text = element_text(size = 5))
# 
# ggarrange(x,tbl,
#           widths = c(1, .3),
#           heights = c(1,.5,.3)) 
#ggsave("BbIncidenceTicksPlotID_v1.pdf", dpi = 320)

```


lets see the difference between 
```{r}
unique(Tick_path_col$testPathogenName)
  Tick_path_col_bmbb <- Tick_path_col[which(Tick_path_col$testPathogenName == 'Borrelia miyamotoi' |
                                        Tick_path_col$testPathogenName == 'Borrelia burgdorferi sensu lato'),]
Tick_path_col_bmbb <- Tick_path_col_bmbb[which(Tick_path_col_bmbb$incidence > "0"),]

ggplot(Tick_path_col_bmbb, aes(y = incidence, x = site, group = testPathogenName, color = testPathogenName))+
  geom_jitter(na.rm = TRUE, width = .4, alpha = .3)+
    clean_background+
    labs(y = 'Pathogen incidence rate', x = 'Site')+
    titleytheme+ xtitletheme+ rotatexaxistheme+
      theme(legend.position = 'bottom', legend.box = 'horizontal',
            legend.title = element_text(size = 6), legend.text = element_text(size = 5))

# group by Pathogen type

Tick_path_col_bmbb$type <- ifelse(Tick_path_col_bmbb$testPathogenName == 'Borrelia miyamotoi', 1, 0)
Tick_path_col_bmbb$type <- ifelse(Tick_path_col_bmbb$testPathogenName == 'Borrelia burgdorferi sensu lato', 1, 0)

Tick_path_col_bmbb$type <- ifelse(Tick_path_col_bmbb$testPathogenName == 'Borrelia miyamotoi', 1, 
                                  ifelse(Tick_path_col_bmbb$testPathogenName == 'Borrelia burgdorferi sensu lato', 2, 0))


compare <- Tick_path_col_bmbb %>%
  group_by(plotID, Date) %>%
    summarise(sum_ = sum(type), .groups = 'drop') %>%
  filter(sum_ > 2)

unique(compare$plotID)
# sites with both bb and bm sampled on Date
#"BLAN_005" "HARV_002" "HARV_004" "SCBI_013" "SERC_001" "SERC_002" "SERC_005" "SERC_012" "SERC_023" "TREE_015" "TREE_017" "TREE_019" #"TREE_022"


both <- Tick_path_col_bmbb[which(Tick_path_col_bmbb$plotID == "BLAN_005"|
                                   Tick_path_col_bmbb$plotID == "HARV_002" |
                                   Tick_path_col_bmbb$plotID == "HARV_004" |
                                   Tick_path_col_bmbb$plotID == "SCBI_013" |
                                   Tick_path_col_bmbb$plotID == "SERC_001" |
                                   Tick_path_col_bmbb$plotID == "SERC_002" |
                                   Tick_path_col_bmbb$plotID == "SERC_005" |
                                   Tick_path_col_bmbb$plotID == "SERC_012" |
                                   Tick_path_col_bmbb$plotID == "SERC_023" |
                                   Tick_path_col_bmbb$plotID == "TREE_015" |
                                   Tick_path_col_bmbb$plotID == "TREE_017" |
                                   Tick_path_col_bmbb$plotID == "TREE_019" |
                                   Tick_path_col_bmbb$plotID == "TREE_022"),]

both %>%
  group_by(Date, testPathogenName)

data_wide <- spread(both, testPathogenName, incidence)


   excel <-data_wide %>%
  group_by(plotID, Date) 
  
install.packages('writexl')
library(writexl)
write_xlsx(excel, " ~Desktop\\excel.xlsx")

```


neon data
```{r}
library(readr)
neon_diff<- read.csv("neon_difference_bbbm.csv")

neon_diff$region[neon_diff$site == "HARV"] <- "northeast"
neon_diff$region[neon_diff$site == "BLAN"] <- "northeast"
neon_diff$region[neon_diff$site == "SCBI"] <- "northeast"
neon_diff$region[neon_diff$site == "SERC"] <- "northeast" 
neon_diff$region[neon_diff$site == "TREE"] <- "midwest"

#unique(neon_diff$site)
ggplot(neon_diff, aes(x = site, y = 100*(diff)))+
  geom_jitter()+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "Region", y = "Difference in prevalence (%)", title = "Difference between Bb and Bm prevalence by site",
       color = "Life Stage")
#ggsave("PathogenDifferenceRegionPublished_v1.pdf", dpi = 320)

ggplot(neon_diff, aes(x = plotID, y = 100*(diff)))+
  geom_jitter()+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "Region", y = "Difference in prevalence (%)", title = "Difference between Bb and Bm prevalence by site",
       color = "Life Stage")+
  rotatexaxistheme

ggplot(neon_diff, aes(x = region, y = 100*(diff)))+
  geom_jitter(size = 3, width = .1)+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "Region", y = "Difference in prevalence (%)", title = "Difference between Bb and Bm prevalence by site",
       color = "Life Stage")+
  xlim("midatlantic","midwest", "northeast")
#

```


published data
```{r}
published_diff <- read.csv("clean_published_difference_bbbm.csv")

ggplot(published_diff, aes(x = state, y = diff, group = lifestage, color = lifestage))+
         geom_point()+
         rotatexaxistheme

#coeff<- 1

# difference between lifestages across regions
ggplot(published_diff, aes(x = region, y = diff), group = lifestage, color = lifestage)+
         #geom_point(size = 3, alpha = .5)+
  geom_jitter(data = neon_diff, aes(x = region, y = 100*(diff)), color = 'blue', size = 3)+
        geom_jitter(width = .4,alpha = 0.5, aes(size = tot_nymph, color = lifestage))+
        scale_size(range = c(3, 10),name = 'Total Ticks Sampled',
             breaks = c(100,500,1000))+
  xlim("westcoast", "midwest", "northeast")+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "Region", y = "Difference in prevalence (%)", title = "Difference between Bb and Bm prevalence by site \n(Published Data)",
       color = "Life Stage")+
  geom_point(x = .5, y = 85, color = 'blue', size = 3, alpha = .3)+
  annotate(geom = "text", x = .79, y = 85, label = "Neon Data", size = 4, hjust = "center")+
  geom_hline(yintercept = 11, alpha = .3 ) +
  geom_hline(yintercept = 47, alpha = .3 ) +
  scale_x_discrete(limits = c("westcoast", "midwest", "northeast"),
    labels = c("West", "Midwest", "Northeast"))+
  guides(color = guide_legend(order = 1))
ggsave("PathogenDifferenceRegionPublished_v2.pdf", dpi = 320)

```



```{r}
# difference between lifestages across states
ggplot(published_diff, aes(x = state, y = diff), group = lifestage, color = lifestage)+
         #geom_point(size = 3, alpha = .5)+
        geom_jitter(width = .29,alpha = 0.5, aes(size = tot_nymph, color = lifestage))+
        scale_size(range = c(3, 10),name = 'Total Ticks Sampled',
             breaks = c(100,500,1000))+
    #geom_jitter(stat = 'identity', data = published_diff, aes(x = region, y = bm_prev), color = 'red',size = 3, alpha = .5)+
    #geom_jitter(stat = 'identity',data = published_diff, aes(x = region, y = bb_prev), color = 'blue',size = 3, alpha = .5)+
         #rotatexaxistheme+
  #scale_y_continuous(name = "Difference in prevalence",
                     #sec.axis = sec_axis(~.*coeff, name = "Prevalence"))+
  #xlim("westcoast", "midwest", "northeast")+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "State", y = "Difference in prevalence (%)", title = "Difference between Bb and Bm prevalence by state",
       color = "Life Stage")



# prevalence difference between bb and bm 
ggplot(published_diff, aes(x = region))+
    geom_jitter(stat = 'identity', data = published_diff, aes(x = region, y = bm_prev, color = 'B. miyamotoi'),size = 3, alpha = .5)+
    geom_jitter(stat = 'identity',data = published_diff, aes(x = region, y = bb_prev, color = 'B. burgdorferi'),size = 3, alpha = .5)+
         #rotatexaxistheme+
  #scale_y_continuous(name = "Difference in prevalence",
                     #sec.axis = sec_axis(~.*coeff, name = "Prevalence"))+
  xlim("westcoast", "midwest", "northeast")+
  clean_background + xtitletheme + ytitletheme +
  labs(x = "Region", y = "Infection Prevalence (%)", title = "Bb and Bm prevalence by site",
       color = "Pathogen Type")

```



```{r}

# two y axis
# coeff <- 
  #scale_y_continuous(name = "Difference in prevalence",
                     #sec.axis = sec_axis(~.*coeff, name = "Prevalence"))+
# unique(Tick_path_col_bmbb$plotID)
# 
# library(janitor)
# bm <- Tick_path_col_bmbb %>%
#   group_by(plotID, testPathogenName) %>%
#   filter(testPathogenName == 'Borrelia miyamotoi')
# 
# unique(bm$plotID)
# unique(bb$plotID)
# 
# bb <- Tick_path_col_bmbb %>%
#   group_by(plotID, testPathogenName) %>%
#   filter(testPathogenName == 'Borrelia burgdorferi sensu lato')
# 
# compare_df_cols(bm, bb)
# 
# install.packages('diffdf')
# library(diffdf)
# 
# diffdf(bm, bb)
# 
# install.packages('arsenal')
# library(arsenal)
# 
# summary(comparedf(bm, bb, by = 'plotID'))
```

